name: commit-workflow
run-name: ${{ github.actor }} pushed a commit
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    name: OTP / Elixir 
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 26
          elixir-version: 1.16.0
      - run: mix deps.get
      - run: mix test